---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "side-script-gke-cl-service-dev"
  namespace: "default"
  labels:
    app: "side-script-gke-cl-dply-dev"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "side-script-gke-cl-dply-dev"
  type: "LoadBalancer"
  loadBalancerIP: ""

